language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
addons:
  chrome: stable
  hostname: localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm run start &
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:ci