language: node_js
node_js:
  - 11
dist: xenial
services:
    - xvfb
sudo: required
addons:
  hostname: localhost
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test