language: node_js
node_js:
  - 11
dist: xenial
services:
    - xvfb
sudo: required
addons:
  hostname: localhost
before_script:
  - npm run start &
  - sleep 15
install:
  - npm install
script:
  - npm run test