language: node_js
node_js:
- 11
env: 
- SERVER_IP_ADDRESS=159.203.99.76
dist: xenial
sudo: required
cache:
  npm: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@159.203.99.76 pwd
install:
- npm install
script:
- npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
after_success:
- cd /var/www/react-jayclim
- git pull origin master
- npm run build
- service apache2 restart

