language: node_js
node_js:
    - 11
dist: xenial
sudo: required
addons:
  chrome: stable
  hostname: localhost
services:
  - xvfb
before_script:
    - npm run start &
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
    - npm install
script:
    - npm run test